# Generated by Django 4.1.2 on 2022-11-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='sequence',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
