# Generated by Django 4.1.2 on 2022-12-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_remove_category_id_alter_category_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('length', 'sequence', 'case', 'type')},
        ),
    ]
