# Generated by Django 4.1.2 on 2022-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0006_remove_category_unique sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='sequence',
            field=models.CharField(max_length=100),
        ),
    ]
