# Generated by Django 4.1.2 on 2022-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0007_category_id_alter_category_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='sequence',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
